# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinDataViz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, choices=[('H1', 'Human One'), ('H2', 'Human Second'), ('S1', 'Software One')], default='', max_length=200)),
                ('created_by_version', models.CharField(max_length=200)),
                ('viz_category', models.CharField(blank=True, default='', max_length=200)),
                ('vis_file', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
